rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::armor_detector::GetCameraFrame -> armor_detect

armor_detect:
  ros__parameters:
    invert_image: false
    exposure_time: 5000
    gain: 1.0
    brightness_threshold: 254       # 数值越小代表适应越暗的环境，160以下旋转矩形会抖动（矩形太大了），往上调试,200以上并没多大差别,上限255
    min_contour_area: 10.0      
    enermy_color: blue              # 调试主要针对蓝色，red_mask我还没怎么调，效果一般
    red_lower1: [0, 100, 100]   
    red_upper1: [40, 255, 255]   
    red_lower2: [160, 100, 100]  
    red_upper2: [180, 255, 255] 
    blue_lower: [80, 0, 0]   
    blue_upper: [160, 255, 255]  
    
